### ISSUE TITLE
RssFeed utf8decode missing and Article page font size change not responding in some feeds

### ISSUE THREAD

**Issue by smurat** [sbeam-dev/SbeamRSS#3]
firstly good project. i noticed these two issue

**Comment by SuperAIdesu** [comment]
Thank you for your feedback! Regarding the first issue, would you please further explain the expected behavior of utf8 decoding? As for the second issue, we would be glad of you could submit the link of an example feed so that we can reproduce the issue. It may be related to the external pub library used to display feed contents.
Best regards!

**Comment by smurat** [comment]
this is my screen record. 
[https://streamable.com/r74nt](https://streamable.com/r74nt)
I also noticed font family change not responding too



I cloned repo and added the code below  in picture for fixing charecter issue .you used this already for atomfeed


![sbeam-dev SbeamRSS](https://user-images.githubusercontent.com/51034904/74433941-771f4e00-4e72-11ea-9292-646cd67d9f5c.png)

Tested feeds

[Mynet](https://www.mynet.com/haber/rss/sondakika)    RssFeed    issue 2 (fontsize and fontfamily doesn't change)
[CnnTurk](https://www.cnnturk.com/feed/rss/)        RssFeed  **Fixed after for me** utf8decode but issue 2 still there
[NTV](https://www.ntv.com.tr/gundem.rss)  AtomFeed    **Works without problem**

I love RSS and also Flutter. loooking forward for the future updates

**Comment by SuperAIdesu** [comment]
Thank you for your detailed reply. We will address this issue soon. The utf8 issue seems simple but the font size issue is a bit more complicated. Further changes will be updated in this page.

**Comment by SuperAIdesu** [comment]
The latest commit has fixed both issues.

Some details on issue 2:

The Mynet and CnnTurk feeds only contain a short description. The descriptions are in plain text format, which is different from other HTML formatted "description"s. We have previously assumed that this kind of feeds may not be displayed correctly, so we made a recommendation in the documentation page for users to choose feeds with "full text" contained. The fix in the latest commit, manually identifies those feeds without HTML tags and wraps a `<p>` tag to them before sending to the flutter_html library. It's not elegant but at least working.

Anyway, thanks for your contribution to this project. The commit will be contained in the next release version. If there are no other issues, we may close the issue in a few hours.

**Comment by smurat** [comment]
thanks SuperAIdesu for quick response and fixing. I'll be watching for project's next features implementing. Best regards..
